apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo.fullname" . }}
spec:
  serviceName: {{ include "mongo.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "mongo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongo.fullname" . }}
    spec:
      containers:
        - name: mongo
          image: {{ .Values.image }}
          command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo.fullname" . }}
spec:
  selector:
    app: {{ include "mongo.fullname" . }}
  ports:
    - port: 27017
      targetPort: 27017
