CREATE USER nessie WITH PASSWORD 'nessie';
CREATE DATABASE nessie OWNER nessie;
GRANT ALL PRIVILEGES ON DATABASE nessie TO nessie;
CREATE USER airflow WITH PASSWORD 'airflow';
CREATE DATABASE airflow OWNER airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
