apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  serviceName: {{ include "postgres.fullname" . }}
  selector:
    matchLabels:
      app: {{ include "postgres.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres.fullname" . }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.database | quote }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "postgres.fullname" . }}
